spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/inventorying_repository
    username: postgres
    password: postgres
  jpa:
    open-in-view: true
  liquibase:
    change-log: classpath:/liquibase/db-changelog.yml