spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/inventorying_repository
    username: postgres
    password: postgres
  jpa:
    open-in-view: true
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
